"use client";

import { useState } from "react";
import "./admin.css";

type Module = "dashboard" | "employees" | "attendance" | "leaves" | "schedules" | "devices" | "settings";

const modules: Array<[Module, string, string]> = [
  ["dashboard", "Dashboard", "▦"], ["employees", "Employees", "♙"], ["attendance", "Attendance", "◷"],
  ["leaves", "Leave management", "▣"], ["schedules", "Work schedules", "▤"], ["devices", "Kiosk devices", "▥"], ["settings", "Settings", "⚙"],
];

export default function AdminPage() {
  const [module, setModule] = useState<Module>("dashboard");
  const [notice, setNotice] = useState("Balkania Admin is ready for your Supabase data connection.");
  return <main className="admin-shell">
    <aside className="admin-sidebar"><div className="admin-brand"><span>B</span><b>Balkania</b></div><p>HR ADMIN</p>{modules.map(([id, label, icon]) => <button key={id} className={module === id ? "active" : ""} onClick={() => setModule(id)}><i>{icon}</i>{label}</button>)}<div className="sidebar-footer">Single tenant · Balkania</div></aside>
    <section className="admin-main"><header className="admin-header"><div><p className="eyebrow">BALKANIA ADMIN</p><h1>{modules.find(([id]) => id === module)?.[1]}</h1></div><div className="admin-actions"><button className="outline-button">▣ Export</button><button className="avatar">HR</button></div></header><p className="admin-notice">{notice}</p>
      {module === "dashboard" && <Dashboard onNavigate={setModule} />}
      {module === "employees" && <Employees setNotice={setNotice} />}
      {module === "attendance" && <Attendance setNotice={setNotice} />}
      {module === "leaves" && <Leaves setNotice={setNotice} />}
      {module === "schedules" && <Schedules setNotice={setNotice} />}
      {module === "devices" && <Devices setNotice={setNotice} />}
      {module === "settings" && <Settings setNotice={setNotice} />}
    </section>
  </main>;
}

function Dashboard({ onNavigate }: { onNavigate: (module: Module) => void }) { return <><div className="admin-stats"><Stat label="Active employees" value="42" note="33 archived" /><Stat label="Working now" value="5" note="24 not clocked in" /><Stat label="Leave requests" value="43" note="Awaiting review" /><Stat label="Attendance rate" value="82%" note="Current month" /></div><div className="admin-grid"><section className="panel wide"><div className="panel-title"><h2>Today&apos;s attendance</h2><button onClick={() => onNavigate("attendance")}>View report →</button></div><div className="attendance-bars"><Bar label="On time" value="53%" /><Bar label="Late" value="6%" warn /><Bar label="Absent" value="41%" danger /></div></section><section className="panel"><div className="panel-title"><h2>Quick actions</h2></div><button className="quick" onClick={() => onNavigate("employees")}>＋ Add employee</button><button className="quick" onClick={() => onNavigate("leaves")}>✓ Review leave</button><button className="quick" onClick={() => onNavigate("devices")}>▥ Manage kiosk</button></section><section className="panel"><div className="panel-title"><h2>Expiring items</h2></div><p className="muted">No contracts or documents require attention.</p></section></div></> }
function Employees({ setNotice }: NoticeProps) { return <><Toolbar action="＋ Add employee" onAction={() => setNotice("Employee creation form will save to Supabase after your authentication setup.")} /><section className="panel"><div className="table-head"><b>Employee</b><b>Department</b><b>Schedule</b><b>Status</b></div>{["Mohamed Ali Maow", "Alex Mathasseril Thomas", "Ahmad Hassan", "Hussein Yusuf Mohammed"].map((name, i) => <div className="table-row" key={name}><span><i className="person-dot">{name[0]}</i>{name}</span><span>{["Operations", "Human Resource", "Sales", "Purchasing"][i]}</span><span>Standard 09:00–17:00</span><span className="pill success">Active</span></div>)}</section></> }
function Attendance({ setNotice }: NoticeProps) { return <><Toolbar action="Review exceptions" onAction={() => setNotice("Attendance exceptions will be loaded from attendance_sessions and attendance_events.")} /><div className="admin-stats"><Stat label="Currently working" value="5" note="Live sessions" /><Stat label="Work completed" value="11" note="Today" /><Stat label="Missing clock-in" value="24" note="Needs review" /></div><section className="panel"><div className="panel-title"><h2>Attendance records</h2><span className="filter">Today ▾</span></div><div className="table-head"><b>Employee</b><b>Clock in</b><b>Working time</b><b>Status</b></div><div className="table-row"><span>Mohamed Ali Maow</span><span>08:07</span><span>7h 24m</span><span className="pill success">On time</span></div><div className="table-row"><span>Alex Mathasseril Thomas</span><span>09:16</span><span>6h 15m</span><span className="pill warning">Late</span></div></section></> }
function Leaves({ setNotice }: NoticeProps) { return <><Toolbar action="Review selected" onAction={() => setNotice("Leave approvals will call the authenticated Supabase approval workflow.")} /><div className="admin-stats"><Stat label="Pending requests" value="43" note="Needs a decision" /><Stat label="On leave today" value="0" note="Approved" /><Stat label="Medical leave" value="0" note="This month" /></div><section className="panel"><div className="table-head"><b>Employee</b><b>Leave type</b><b>Dates</b><b>Status</b></div><div className="table-row"><span>Mohamed Ali Maow</span><span>Annual leave</span><span>18–20 Aug 2026</span><span className="pill pending">Pending</span></div></section></> }
function Schedules({ setNotice }: NoticeProps) { return <><Toolbar action="＋ Create shift" onAction={() => setNotice("Shift templates and assignments are ready to connect to the schedules tables.")} /><section className="panel"><div className="panel-title"><h2>Working templates</h2><span className="filter">All branches ▾</span></div><div className="schedule-row"><b>Standard office</b><span>Mon–Fri · 09:00–17:00</span><span className="pill success">Default</span></div><div className="schedule-row"><b>Warehouse workers</b><span>Mon–Sat · 08:00–16:00</span><span className="pill">Active</span></div></section></> }
function Devices({ setNotice }: NoticeProps) { return <><Toolbar action="＋ Register kiosk" onAction={() => setNotice("Kiosk registration will create a restricted attendance_devices record and one-time PIN.")} /><section className="panel"><div className="panel-title"><h2>QR attendance devices</h2><span className="pill success">QR mode enabled</span></div><p className="muted">Employees show their rotating personal QR code. A dedicated tablet scans it and records the server-validated attendance event.</p><div className="device-card"><div><b>Front entrance tablet</b><p className="muted">Restricted kiosk account · Last sync: never</p></div><button className="outline-button">Regenerate PIN</button></div><section className="setting-card"><div><b>Optional geolocation rule</b><p className="muted">Enable later to limit direct mobile clock-ins to approved locations.</p></div><label className="switch"><input type="checkbox" /><span /></label></section></section></> }
function Settings({ setNotice }: NoticeProps) { return <section className="panel settings-panel"><Setting title="Company details" text="HR representative, leave year and date format" /><Setting title="Attendance rules" text="QR kiosk, mobile buttons, web check-in and geolocation" /><Setting title="Leave policies" text="Types, entitlements, approvals and holidays" /><Setting title="Audit log" text="Review sensitive platform activity" /><button className="primary-admin" onClick={() => setNotice("Settings persist after the Supabase project and your authentication are configured.")}>Save settings</button></section> }
function Toolbar({ action, onAction }: { action: string; onAction: () => void }) { return <div className="toolbar"><input placeholder="Search" /><button className="outline-button">Filters</button><button className="primary-admin" onClick={onAction}>{action}</button></div> }
function Stat({ label, value, note }: { label: string; value: string; note: string }) { return <section className="stat"><p>{label}</p><strong>{value}</strong><small>{note}</small></section> }
function Bar({ label, value, warn, danger }: { label: string; value: string; warn?: boolean; danger?: boolean }) { return <div className="bar"><span>{label}</span><div><i className={danger ? "danger" : warn ? "warn" : ""} style={{ width: value }} /></div><b>{value}</b></div> }
function Setting({ title, text }: { title: string; text: string }) { return <button><span><b>{title}</b><small>{text}</small></span><i>›</i></button> }
type NoticeProps = { setNotice: (value: string) => void };
